
name: deploy vue
on:
  push:
    branches:
      - master
    

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v2
      
      - name: build the code      
        run: | 
          yarn install
          yarn run build
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER_NAME}}          
          key: ${{secrets.SSH_KEY}}
          source: "./dist/*"
          target: "/var/www/html"
          strip_components: 1
